unique_ids:
  assets:
    standard-page.html: 7YF55Z3OO4OZHTS4QSDOBN3MASNCYBP7
    theme.css: 5FTKH3F4MYBFSCSYFYD2CN27GSHUUR4G
  forms:
    Form1: 7DBAKK6X4RYDS3MR76BKIGTMMMOI4YXK
  modules: {}
  scripts: {}
  server_modules: {}
